#!/usr/bin/env node
// Script pour bundler les fichiers content/ en un seul fichier content-bundled.js
// Usage: node build-content.js

const fs = require('fs');
const path = require('path');

console.log('🔨 Building content bundle...');

// Ordre de chargement des fichiers (important pour les dépendances)
const filesOrder = [
  'config.js',        // CONFIG et state doivent être en premier
  'utils.js',         // Utilitaires de base
  'darkMode.js',      // Dark mode
  'wallet.js',        // Wallet balance
  'settings.js',      // Settings manager
  'sidebarTabs.js',  // Sidebar tabs system
  'orders.js',        // Orders management
  'wardrobe.js',      // Wardrobe items
  'notifications.js', // Notifications widget
  'messages.js',      // Messages and conversations (contient getCsrfToken)
  'offer.js',         // Offer options (utilise getCsrfToken de messages.js)
  'buyButton.js',     // Buy button toggle
  'api.js',           // API calls
  'itemManager.js',   // Item manager
  'monitor.js',       // Monitor system
  'filterManager.js', // Filter manager
  'alertSystem.js',   // Alert system
  'pickupPoints.js',  // Pickup points
  'ui.js',            // UI components
  'init.js'           // Initialization
];

const contentDir = path.join(__dirname, 'content');
const bundle = [];

// En-tête du bundle
bundle.push(`// ==========================================
// VINTED CONTENT SCRIPT - BUNDLED VERSION
// Auto-generated by build-content.js
// Do not edit this file directly - edit files in content/ directory
// ==========================================

(function() {
  'use strict';
  
`);

// Lire et ajouter chaque fichier dans l'ordre
filesOrder.forEach((filename, index) => {
  const filePath = path.join(contentDir, filename);
  
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  File not found: ${filePath}`);
    return;
  }
  
  const fileContent = fs.readFileSync(filePath, 'utf8');
  
  // Ajouter un commentaire de section
  bundle.push(`  // ==========================================
  // ${filename}
  // ==========================================
  
`);
  
  // Ajouter le contenu du fichier
  bundle.push(`  ${fileContent.split('\n').join('\n  ')}`);
  
  // Ajouter une ligne vide entre les fichiers
  if (index < filesOrder.length - 1) {
    bundle.push('\n\n');
  }
});

// Fermer l'IIFE
bundle.push(`

})();
`);

// Écrire le bundle
const outputPath = path.join(__dirname, 'content-bundled.js');
const bundleContent = bundle.join('');
fs.writeFileSync(outputPath, bundleContent, 'utf8');

console.log('✅ Bundle created:', outputPath);
console.log('📦 Size:', (bundleContent.length / 1024).toFixed(2), 'KB');
console.log(`📄 Files bundled: ${filesOrder.length}`);

